name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: retypeapp/action-build@latest
      - name: Clear .gitignore
        run: |
          cat .gitignore | sed 's/public//g' >> .gitignore
      - uses: retypeapp/action-github-pages@latest
        with:
          branch: public
          update-branch: true